/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void task2Test() {
        // Arrange
        List<String> input = Arrays.asList("apple", "banana", "cherry");
        List<String> expected = Arrays.asList("pple", "anana", "herry");
        // Act
        List<String> result = SimpleFunctions.Task2(input);
        // Assert
        assertEquals(expected, result);
    }
    @Test
    void task2Test() {
        // Arrange
        List<String> input = Arrays.asList("a", "", "cat", "d");
        List<String> expected = Arrays.asList("", "at");
        // Act
        List<String> result = SimpleFunctions.Task2(input);
        // Assert
        assertEquals(expected, result);
    }
    @Test
    public void testTask3(){
        //arrange
        String testBasic = "()";
        String testWrong = "(";
        String testNested = "((()))";

        //act and assert as it returns boolean
        assertTrue(Task3(testBasic));
        assertFalse(Task3(testWrong));
        assertTrue(Task3(testNested));
    }
}
